version: '3'
services:
  database:
    container_name: database_dev
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    volumes:
      - 'database1:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: spring
      POSTGRESQL_PASSWORD: 1234
      POSTGRESQL_POSTGRES_PASSWORD: 1234
      POSTGRESQL_DATABASE: "database_dev"
    ports:
      - "5475:5432"
    networks:
      - application_ds

  database_casadocodigo_test:
    container_name: database_casadocodigo_test
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    volumes:
      - 'database_casadocodigo_test1:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: spring
      POSTGRESQL_PASSWORD: 1234
      POSTGRESQL_POSTGRES_PASSWORD: 1234
      POSTGRESQL_DATABASE: "database_test"
    ports:
      - "5401:5432"
    networks:
      - application_ds
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: lucas.mezuraro@zup.com.br
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8000:80"
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    links:
      - 'database:dev'
      - 'database_casadocodigo_test:test'
networks:
  application_ds:
    driver: bridge
volumes:
  database_casadocodigo_test1:
    driver: local
  database1:
    driver: local
  pgadmin-data: