spring:
  application:
    name: "CasaDoCodigo"
  datasource:
    url: jdbc:postgresql://localhost:5475/turbex_receiver_service
    username: "postgres"
    password: 1234
    jpa:
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
        ddl-auto: update